# Generated by Django 6.0.4 on 2026-05-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
