# Generated by Django 6.0.4 on 2026-05-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
