# Generated by Django 6.0.4 on 2026-04-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file_path',
            new_name='file',
        ),
    ]
